config/routes.rb
Rails.application.routes.draw do
    get 'notification/index'
    get 'notification/background_job'
    post 'notification/create'
    root 'statistic#home'
    get 'login', to: 'session#new'
    post 'login', to: 'session#create'
    delete 'logout', to: 'session#destroy'
    resource 'allowances', only: [:show]
    resource 'vouchers', only: [:show, :create]
    resource 'users'
    resource 'dishes'
    resource 'tables'
    resource 'categories'
    resource 'price_change_histories'
    resource 'materials'
    resource 'feed_backs', only: [:show]
    post 'notify_webapp', to: 'pay_pal#notify_webapp'
    get 'refund', to: 'pay_pal#refund'
    get 'rejected_order', to: 'pay_pal#rejected_order'
    get 'send_money', to: 'pay_pal#send_money'
    get 'getEmail', to: 'pay_pal#getEmail'
    get 'balance', to: 'users#user_balance'
    get 'withdraw', to: 'users#with_draw'
    post 'executeSendMoney', to: 'pay_pal#executeSend'
    get 'make_statistic', to: 'statistic#make_statistic'
    get 'setScheduler', to: 'statistic#setScheduler'
    get 'scheduler', to: 'statistic#scheduler'
    get 'home', to: 'statistic#home'
    get 'dashboard', to: 'statistic#index'
    get 'current_order', to: 'statistic#current_order'
    get 'cancel_order', to: 'pay_pal#cancel_order'
    resources :fakes, only: [:index]
    devise_for :users
    require 'sidekiq/web'
    mount Sidekiq::Web => '/side'

    namespace :api do
        scope module: :v1, constraints: ApiConstraint.new(version: :v1) do
            get 'home', to: 'home#index'
            resources :users, only: [:show, :create, :update] do
                collection do
                    get :balance
                    post :add_voucher
                end
            end

            resources :vouchers do
                collection do
                    post :check_balance_code
                end

            end

            resources :feedbacks, only: [:create] do
                
            end
            resources :sessions, only: [:create, :destroy]
            resources :dishes, only: [:index, :show, :update, :destroy] do
                member do
                    get :cutlery
                    get :drinking
                end
                collection do
                    get :by_category
                    get :as_cart
                    get :search_cutlery
                    get :search_drinking
                    get :search_all
                    post :register_reg_token
                    post :disable_dish
                    get :check_dish_available
                    get :dish_suggestion
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :orders, only: [:create, :index] do
                collection do
                    get :order_history
                    post :dish_done # mon an duoc lam xong
                    post :list_dish_done
                    post :remove_dish # mon an remove khoi menu vi nhet nguyen lieu
                    post :reject_order # order bi reject boi chef
                    get :all_order # get toan bo order
                    post :mark_order_accept
                    post :mark_order_reject
                    get :order_in_time
                    get :is_in_time_order
                    post :fully_refund
                    post :partial_refund
                    get :table_dish
                    post :notify_order_detail_not_available
                    post :mark_order_detail_served
                    post :mark_list_order_detail_served
                    post :create_by_cash
                    post :create_by_voucher
                    post :payed_by_cash
                    post :keep_order_detail
                    post :cash_full_refund
                    post :cash_partial_refund
                end
            end

            resources :materials, only: [:index] do
                collection do
                    post :mark_not_available
                    post :mark_available
                end
            end

        end
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  provider               :string           default("email"), not null
#  uid                    :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ipd    :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  full_name              :string
#  avatar                 :string
#  email                  :string
#  username               :string
#  access_token           :string
#  reg_token              :string
#  birthdate              :string
#  mark                   :float            default(0.0)
#  phone                  :string
#  tokens                 :json
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role_id                :integer
#  balance                :decimal(, )      default(0.0)
#
# Indexes
#
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_role_id               (role_id)
#  index_users_on_uid_and_provider      (uid,provider) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#  index_users_on_username              (username)
#

class User < ActiveRecord::Base
  mount_uploader :avatar, ImageUploader
  # Include default devise modules.
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :omniauthable
  # :confirmable, , :token_authenticatable

  include DeviseTokenAuth::Concerns::User

  validates :username, uniqueness: {message: 'taken'}
  # validates :first_name, presence: true
  validates :password, confirmation: true

  belongs_to :role, optional: true
  # belongs_to :membership, optional: true

  has_many :orders
  has_many :vouchers
  has_many :feedbacks
  # validates :email, uniqueness: {message: 'taken'}
  # validates :first_name, presence: true

  def self.search(term)
    if term
      where('lower(full_name) LIKE ?', "%#{term.downcase}%")
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApiController
      before_action :execute

      def show
      end

      def create
      end

      def update
      end

      def balance
      end

      def add_voucher
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < WebApplcationController
  before_action 'authen_user'
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Users", :users_path

  def user_balance
    add_breadcrumb "Balance"
    if !params[:term].nil? && params[:term] != ''
      @users = User.search(params[:term]).paginate(page: params[:page], per_page: 10)
    end
  end

  def with_draw
    user = User.find params[:user_id]
    user.balance = 0
    user.save!
    redirect_to balance_path(term: user.full_name)
  end

  def new
    @user = User.new
    add_breadcrumb "New User"
  end

  def create
    @user = User.new user_params
    @user.password = "123123123"
    @user.save
    redirect_to users_path
  end

  def show
    if session[:role] == "manager"
      redirect_to balance_path
    end
    if !params[:term].nil? && params[:term] != ''
      @users = User.search(params[:term]).paginate(page: params[:page], per_page: 10)
    end
  end

  def edit
    @user = User.find params[:id]
    add_breadcrumb @user.username
  end

  def update
    @user = User.find params[:user][:id]
    @user.update_attributes(user_params)
    redirect_to action: 'show'
  end

  def user_params
    params.require(:user).permit :id, :username, :full_name, :role_id, :membership_id, :email, :phone, :birthdate, :avatar, :term, :password, :password_confirmation
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="row">
  <%= form_for @user, url: {controller: 'users', action: 'update'} do |f| %>
      <div class="col s4">
        <div class="card">
          <div class="card-image" style="background-color: gray; min-height: 250px" id="image">
            <%= image_tag @user.avatar, id: 'tmpImage', style: 'min-height: 250px' %>
            <span class="card-title">User Avatar</span>
            <a id="float" class="btn-floating" style="position: absolute; top: 45%; left: 45%; background-color: transparent; box-shadow: none;"><i class="material-icons">add</i></a>
          </div>
        </div>
      </div>
      <div class="col s8">
        <div class="card">
          <div class="card-content">
            <%= f.file_field :avatar, style: 'display: none;', onchange: 'readURL(this)' %>
            <%= f.hidden_field :id %>
            <div class="row">
              <div class="input-field col s6">
                <%= f.label :username, "Username *" %>
                <%= f.text_field :username, value: @user.username %>
              </div>
              <div class="input-field col s6">
                <%= f.label :full_name, "Fullname *" %>
                <%= f.text_field :full_name, value: @user.full_name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s6">
                <%= f.label :email, "Email *" %>
                <%= f.email_field :email, value: @user.email, class: "validate" %>
              </div>
              <div class="input-field col s6">
                <%= f.label :birthdate, "Birthday" %>
                <%= f.date_field :birthdate, value: @user.birthdate, class: "datepicker" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s6">
                <%= collection_select :user, :role_id, Role.all, :id, :name, prompt: true %>
                <label>User Role</label>
              </div>
              <div class="input-field col s6">
                <%= f.label :phone, "Phone" %>
                <%= f.phone_field :phone, value: @user.phone %>
              </div>
            </div>
            <div class="row">
              <div class="col s12">
                <%= link_to 'Back', users_path, class: "btn", data: {turbolinks: false} %>
                <%= f.submit value: 'update', class: 'btn' %>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>
<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
    });
    var $input = $('.datepicker').pickadate();
    // Use the picker object directly.
    var picker = $input.pickadate('picker');
    picker.set('select', $('#user_birthdate').val())
    $('#image').click(function () {
        $('#user_avatar').trigger('click');
    });
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#tmpImage')
                    .attr('src', e.target.result)
            };
            reader.readAsDataURL(input.files[0]);
            $('#float').css('display', 'none');
        }
    }
</script>

app/views/users/new.html.erb
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="row">
  <%= form_for @user do |f| %>
      <div class="col s4">
        <div class="card">
          <div class="card-image" style="background-color: gray; min-height: 250px" id="image">
            <%= image_tag @user.avatar, id: 'tmpImage', style: 'min-height: 250px' %>
            <span class="card-title">User Avatar</span>
            <a id="float" class="btn-floating" style="position: absolute; top: 45%; left: 45%; background-color: transparent; box-shadow: none;"><i class="material-icons">add</i></a>
          </div>
        </div>
      </div>
      <div class="col s8">
        <div class="card">
          <div class="card-content">
            <%= f.file_field :avatar, style: 'display: none;', onchange: 'readURL(this)' %>
            <%= f.hidden_field :id %>
            <div class="row">
              <div class="input-field col s6">
                <%= f.label :username, "Username *" %>
                <%= f.text_field :username, value: @user.username %>
              </div>
              <div class="input-field col s6">
                <%= f.label :full_name, "Fullname *" %>
                <%= f.text_field :full_name, value: @user.full_name %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s6">
                <%= f.label :email, "Email *" %>
                <%= f.email_field :email, value: @user.email, class: "validate" %>
              </div>
              <div class="input-field col s6">
                <%= f.label :birthdate, "Birthday" %>
                <%= f.date_field :birthdate, value: @user.birthdate, class: "datepicker" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s6">
                <%= collection_select :user, :role_id, Role.all, :id, :name, prompt: true %>
                <label>User Role</label>
              </div>
              <div class="input-field col s6">
                <%= f.label :phone, "Phone" %>
                <%= f.phone_field :phone, value: @user.phone %>
              </div>
            </div>
            <div class="row">
              <div class="col s12">
                <%= link_to 'Back', users_path, class: "btn", data: {turbolinks: false} %>
                <%= f.submit value: 'add', class: 'btn' %>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>
<script>
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
    });
    var $input = $('.datepicker').pickadate();
    // Use the picker object directly.
    var picker = $input.pickadate('picker');
    picker.set('select', $('#user_birthdate').val())
    $('#image').click(function () {
        $('#user_avatar').trigger('click');
    });
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#tmpImage')
                    .attr('src', e.target.result)
            };
            reader.readAsDataURL(input.files[0]);
            $('#float').css('display', 'none');
        }
    }
</script>

app/views/users/show.html.erb
<style>
  a li {
    width: 20px;
  }
</style>
<div class="row" style="text-align: right; margin-bottom: 0;">
  <div class="left" style="margin-left: 1%; font-size: 18px">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
  <div class="col s7 right">
    <div class="input-field" style="margin-top: 0;">
      <%= form_tag(users_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], style: 'width: 70%;', placeholder: 'Search', data: {autocomplete_source: User.order(:full_name).map(&:full_name)} %>
          <button type="submit" class="btn-floating waves-effect waves-light">
            <i class="material-icons">search</i>
          </button>
          <%= link_to new_users_path, data: {turbolinks: false} do %>
              <input type="button" class="btn" value="Add">
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<div style="padding: 0 1%;">
  <% if !@users.nil? && @users.size > 0 %>
      <table class="highlight">
        <thead>
        <th>Username</th>
        <th>Fullname</th>
        <th>Email</th>
        <th>Role</th>
        <th></th>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td><%= user.role.name %></td>
              <td>
                <a href="users/edit?id=<%= user.id %>" data-turbolinks="false">
                  <i class="material-icons">mode_edit</i>
                </a>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="center">
        <%= will_paginate @users %>
      </div>
  <% elsif !params[:term].nil? %>
      <h3 style="text-align: center">No User Found</h3>
  <% end %>
</div>
<script>
    $('#term').autocomplete({
        source: $('#term').data('autocomplete-source')
    });
</script>

app/views/users/user_balance.html.erb
<style>
  a li {
    width: 20px;
  }
</style>
<div id="unclose_modal" class="modal">
  <div class="modal-content" style="text-align: center;">
    <h5>Please Wait...</h5>
    <div class="preloader-wrapper big active">
      <div class="spinner-layer spinner-blue-only">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div>
        <div class="gap-patch">
          <div class="circle"></div>
        </div>
        <div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row" style="text-align: right; margin-bottom: 0;">
  <div class="left" style="margin-left: 1%; font-size: 18px">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
  <div class="col s7 right">
    <div class="input-field" style="margin-top: 0;">
      <%= form_tag(balance_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], style: 'width: 70%;', placeholder: 'Search', data: {autocomplete_source: User.order(:full_name).map(&:full_name)} %>
          <button type="submit" class="btn-floating waves-effect waves-light">
            <i class="material-icons">search</i>
          </button>
      <% end %>
    </div>
  </div>
</div>
<div style="padding: 0 1%;">
  <% if !@users.nil? && @users.size > 0 %>
      <table class="highlight">
        <thead>
        <th>Username</th>
        <th>Fullname</th>
        <th>Email</th>
        <th>Balance</th>
        <th></th>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td><%= "#{number_to_currency(user.balance, unit: '', precision: 0)} VND" %></td>
              <td style="text-align: center">
                <a href="withdraw?user_id=<%= user.id %>" onclick="$('#unclose_modal').modal('open')">
                  <button class="btn red">Withdraw</button>
                </a>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="center">
        <%= will_paginate @users %>
      </div>
  <% elsif !params[:term].nil? %>
      <h3 style="text-align: center">No User Found</h3>
  <% end %>
</div>
<script>
    $('#term').autocomplete({
        source: $('#term').data('autocomplete-source')
    });
</script>