config/routes.rb
Rails.application.routes.draw do
    get 'notification/index'
    get 'notification/background_job'
    post 'notification/create'
    root 'statistic#home'
    get 'login', to: 'session#new'
    post 'login', to: 'session#create'
    delete 'logout', to: 'session#destroy'
    resource 'allowances', only: [:show]
    resource 'vouchers', only: [:show, :create]
    resource 'users'
    resource 'dishes'
    resource 'tables'
    resource 'categories'
    resource 'price_change_histories'
    resource 'materials'
    resource 'feed_backs', only: [:show]
    post 'notify_webapp', to: 'pay_pal#notify_webapp'
    get 'refund', to: 'pay_pal#refund'
    get 'rejected_order', to: 'pay_pal#rejected_order'
    get 'send_money', to: 'pay_pal#send_money'
    get 'getEmail', to: 'pay_pal#getEmail'
    get 'balance', to: 'users#user_balance'
    get 'withdraw', to: 'users#with_draw'
    post 'executeSendMoney', to: 'pay_pal#executeSend'
    get 'make_statistic', to: 'statistic#make_statistic'
    get 'setScheduler', to: 'statistic#setScheduler'
    get 'scheduler', to: 'statistic#scheduler'
    get 'home', to: 'statistic#home'
    get 'dashboard', to: 'statistic#index'
    get 'current_order', to: 'statistic#current_order'
    get 'cancel_order', to: 'pay_pal#cancel_order'
    resources :fakes, only: [:index]
    devise_for :users
    require 'sidekiq/web'
    mount Sidekiq::Web => '/side'

    namespace :api do
        scope module: :v1, constraints: ApiConstraint.new(version: :v1) do
            get 'home', to: 'home#index'
            resources :users, only: [:show, :create, :update] do
                collection do
                    get :balance
                    post :add_voucher
                end
            end

            resources :vouchers do
                collection do
                    post :check_balance_code
                end

            end

            resources :feedbacks, only: [:create] do
                
            end
            resources :sessions, only: [:create, :destroy]
            resources :dishes, only: [:index, :show, :update, :destroy] do
                member do
                    get :cutlery
                    get :drinking
                end
                collection do
                    get :by_category
                    get :as_cart
                    get :search_cutlery
                    get :search_drinking
                    get :search_all
                    post :register_reg_token
                    post :disable_dish
                    get :check_dish_available
                    get :dish_suggestion
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :orders, only: [:create, :index] do
                collection do
                    get :order_history
                    post :dish_done # mon an duoc lam xong
                    post :list_dish_done
                    post :remove_dish # mon an remove khoi menu vi nhet nguyen lieu
                    post :reject_order # order bi reject boi chef
                    get :all_order # get toan bo order
                    post :mark_order_accept
                    post :mark_order_reject
                    get :order_in_time
                    get :is_in_time_order
                    post :fully_refund
                    post :partial_refund
                    get :table_dish
                    post :notify_order_detail_not_available
                    post :mark_order_detail_served
                    post :mark_list_order_detail_served
                    post :create_by_cash
                    post :create_by_voucher
                    post :payed_by_cash
                    post :keep_order_detail
                    post :cash_full_refund
                    post :cash_partial_refund
                end
            end

            resources :materials, only: [:index] do
                collection do
                    post :mark_not_available
                    post :mark_available
                end
            end

        end
    end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id            :integer          not null, primary key
#  category_name :string
#  status        :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Category < ApplicationRecord
	has_many :dishes

	def self.search(term)
		if term
			where('lower(category_name) LIKE ?', "%#{term.downcase}%")
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action 'authen_user'
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Categories", :categories_path

  def create
    @category = Category.new category_params
    @category.status = true
    @category.save
    redirect_to categories_path
  end

  def show
    if !params[:term].nil? && params[:term] != ''
      @categories = Category.search(params[:term]).paginate(page: params[:page], per_page: 10)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @category = Category.new
    add_breadcrumb "New Category"
  end

  def edit
    @category = Category.find params[:id]
    add_breadcrumb "Category "+ params[:id]
  end

  def update
    @category = Category.find params[:category][:id]
    @category.update_attributes(category_params)
    redirect_to action: 'show'
  end

  private
  def category_params
    params.require(:category).permit :id, :category_name, :status
  end
end

app/views/categories/edit.html.erb
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="container">
  <div class="card">
    <%= form_for @category, url: {controller: 'categories', action: 'update'} do |f| %>
        <%= f.hidden_field :id %>
        <div class="card-content">
          <span class="card-title">Update Category</span>
          <div class="input-field" style="margin-top: 5%;">
            <%= f.label :category_name, "Category Name" %>
            <%= f.text_field :category_name, style: 'width: 50%;', placeholder: 'Category Name' %>
          </div>
          <%= link_to 'Back', categories_path, class: "btn" %>
          <%= f.submit value: 'Update', class: 'btn' %>
        </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="container">
  <div class="card">
    <%= form_for @category do |f| %>
        <div class="card-content">
          <span class="card-title">New Category</span>
          <div class="input-field" style="margin-top: 5%;">
            <%= f.label :category_name, "Category Name" %>
            <%= f.text_field :category_name, style: 'width: 50%;', placeholder: 'Category Name' %>
          </div>
          <%= link_to 'Back', categories_path, class: "btn" %>
          <%= f.submit value: 'Add', class: 'btn' %>
        </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<style>
  a li {
    width: 20px;
  }
</style>
<div class="row" style="text-align: right; margin-bottom: 0;">
  <div class="left" style="margin-left: 1%; font-size: 18px">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
  <div class="col s7 right">
    <div class="input-field" style="margin-top: 0">
      <%= form_tag(categories_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], style: 'width: 70%;', placeholder: 'Search', data: { autocomplete_source: Category.order(:category_name).map(&:category_name)} %>
          <button type="submit" class="btn-floating waves-effect waves-light">
            <i class="material-icons">search</i>
          </button>
          <%= link_to new_categories_path, data: {turbolinks: false} do %>
              <input type="button" class="btn" value="Add">
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<div style="padding: 0 5%;">
  <% if !@categories.nil? && @categories.size > 0 %>
      <table class="bordered striped">
        <thead>
        <th>Category Name</th>
        <th></th>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
            <tr>
              <td><%= category.category_name %></td>
              <td>
                <a href="categories/edit?id=<%= category.id %>" data-turbolinks="false">
                  <i class="material-icons">mode_edit</i>
                </a>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="center">
        <%= will_paginate @categories %>
      </div>
  <% elsif !params[:term].nil? %>
      <h3 style="text-align: center">No Category Found</h3>
  <% end %>
</div>

<script>
    $('#term').autocomplete({
        source: $('#term').data('autocomplete-source')
    });
</script>