config/routes.rb
Rails.application.routes.draw do
    get 'notification/index'
    get 'notification/background_job'
    post 'notification/create'
    root 'statistic#home'
    get 'login', to: 'session#new'
    post 'login', to: 'session#create'
    delete 'logout', to: 'session#destroy'
    resource 'allowances', only: [:show]
    resource 'vouchers', only: [:show, :create]
    resource 'users'
    resource 'dishes'
    resource 'tables'
    resource 'categories'
    resource 'price_change_histories'
    resource 'materials'
    resource 'feed_backs', only: [:show]
    post 'notify_webapp', to: 'pay_pal#notify_webapp'
    get 'refund', to: 'pay_pal#refund'
    get 'rejected_order', to: 'pay_pal#rejected_order'
    get 'send_money', to: 'pay_pal#send_money'
    get 'getEmail', to: 'pay_pal#getEmail'
    get 'balance', to: 'users#user_balance'
    get 'withdraw', to: 'users#with_draw'
    post 'executeSendMoney', to: 'pay_pal#executeSend'
    get 'make_statistic', to: 'statistic#make_statistic'
    get 'setScheduler', to: 'statistic#setScheduler'
    get 'scheduler', to: 'statistic#scheduler'
    get 'home', to: 'statistic#home'
    get 'dashboard', to: 'statistic#index'
    get 'current_order', to: 'statistic#current_order'
    get 'cancel_order', to: 'pay_pal#cancel_order'
    resources :fakes, only: [:index]
    devise_for :users
    require 'sidekiq/web'
    mount Sidekiq::Web => '/side'

    namespace :api do
        scope module: :v1, constraints: ApiConstraint.new(version: :v1) do
            get 'home', to: 'home#index'
            resources :users, only: [:show, :create, :update] do
                collection do
                    get :balance
                    post :add_voucher
                end
            end

            resources :vouchers do
                collection do
                    post :check_balance_code
                end

            end

            resources :feedbacks, only: [:create] do
                
            end
            resources :sessions, only: [:create, :destroy]
            resources :dishes, only: [:index, :show, :update, :destroy] do
                member do
                    get :cutlery
                    get :drinking
                end
                collection do
                    get :by_category
                    get :as_cart
                    get :search_cutlery
                    get :search_drinking
                    get :search_all
                    post :register_reg_token
                    post :disable_dish
                    get :check_dish_available
                    get :dish_suggestion
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :orders, only: [:create, :index] do
                collection do
                    get :order_history
                    post :dish_done # mon an duoc lam xong
                    post :list_dish_done
                    post :remove_dish # mon an remove khoi menu vi nhet nguyen lieu
                    post :reject_order # order bi reject boi chef
                    get :all_order # get toan bo order
                    post :mark_order_accept
                    post :mark_order_reject
                    get :order_in_time
                    get :is_in_time_order
                    post :fully_refund
                    post :partial_refund
                    get :table_dish
                    post :notify_order_detail_not_available
                    post :mark_order_detail_served
                    post :mark_list_order_detail_served
                    post :create_by_cash
                    post :create_by_voucher
                    post :payed_by_cash
                    post :keep_order_detail
                    post :cash_full_refund
                    post :cash_partial_refund
                end
            end

            resources :materials, only: [:index] do
                collection do
                    post :mark_not_available
                    post :mark_available
                end
            end

        end
    end
end

app/models/material.rb
# == Schema Information
#
# Table name: materials
#
#  id         :integer          not null, primary key
#  name       :string
#  available  :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Material < ApplicationRecord
  has_many :dishes

  def self.search(term)
    if term
      where('lower(name) LIKE ?', "%#{term.downcase}%")
    end
  end
end

app/controllers/api/v1/materials_controller.rb
module Api
    module V1
        class MaterialsController < ApiController
            before_action :execute

            def index
            end

            def mark_not_available
            end

            def mark_available
            end
        end
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action 'authen_user'
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Materials", :materials_path

  def create
    @material = Material.new material_params
    @material.available = true
    @material.save
    redirect_to materials_path
  end

  def show
    if !params[:term].nil? && params[:term] != ''
      @materials = Material.search(params[:term]).paginate(page: params[:page], per_page: 10)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @material = Material.new
    add_breadcrumb "New Material"
  end

  def update_status
    respond_to do |format|
      format.json {
        @material = Material.find params[:id]
        if @material.available.nil?
          @material.update available: false
        end
        @material.update available: !@material.available
        render nothing: ''
      }
    end
  end

  def edit
    @material = Material.find params[:id]
    add_breadcrumb @material.name
  end

  def update
    @material = Material.find params[:material][:id]
    @material.update_attributes(material_params)
    redirect_to action: 'show'
  end

  private
  def material_params
    params.require(:material).permit :id, :name, :available
  end
end

app/views/materials/edit.html.erb
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="container">
  <div class="card">
    <%= form_for @material, url: {controller: 'materials', action: 'update'} do |f| %>
        <%= f.hidden_field :id %>
        <div class="card-content">
          <span class="card-title center">Update Material</span>
          <div class="input-field">
            <%= f.label :name, 'Material Name *' %>
            <%= f.text_field :name, required: 'true', placeholder: 'Material Name' %>
          </div>
          <%= link_to 'Back', materials_path, class: "btn", data: {turbolinks: false} %>
          <%= f.submit value: 'update', class: 'btn' %>
        </div>
    <% end %>
  </div>
</div>

app/views/materials/new.html.erb
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="container">
  <div class="card">
    <%= form_for @material do |f| %>
        <div class="card-content">
          <span class="card-title center">New Material</span>
          <div class="input-field">
            <%= f.label :name, 'Material Name *' %>
            <%= f.text_field :name, required: 'true', placeholder: 'Material Name' %>
          </div>
          <%= link_to 'Back', materials_path, class: "btn", data: {turbolinks: false} %>
          <%= f.submit value: 'Add', class: 'btn' %>
        </div>
    <% end %>
  </div>
</div>

app/views/materials/show.html.erb
<style>
  a li {
    width: 20px;
  }
</style>
<div class="row" style="text-align: right; margin-bottom: 0;">
  <div class="left" style="margin-left: 1%; font-size: 18px">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
  <div class="col s7 right">
    <div class="input-field" style="margin-top: 0">
      <%= form_tag(materials_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], style: 'width: 70%;', placeholder: 'Search', data: { autocomplete_source: Material.order(:name).map(&:name)} %>
          <button type="submit" class="btn-floating waves-effect waves-light">
            <i class="material-icons">search</i>
          </button>
          <%= link_to new_materials_path, data: {turbolinks: false} do %>
              <input type="button" class="btn" value="Add">
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<div style="padding: 0 1%;">
  <% if !@materials.nil? && @materials.size > 0 %>
      <table class="bordered striped">
        <thead>
        <th style="text-align: center">Material Name</th>
        <th style="text-align: center">Available</th>
        <th></th>
        </thead>
        <tbody>
        <% @materials.each do |material| %>
            <tr>
              <td><%= material.name %></td>
              <td style="text-align: center">
                <p>
                  <%= check_box_tag material.id, material.available, material.available, onclick: "changeStatus(#{material.id})" %>
                  <label for="<%= material.id %>" id="label<%= material.id %>">
                  </label>
                </p>
              </td>
              <td>
                <a href="materials/edit?id=<%= material.id %>" data-turbolinks="false">
                  <i class="material-icons">mode_edit</i>
                </a>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="center">
        <%= will_paginate @materials %>
      </div>
  <% elsif !params[:term].nil? %>
      <h3 style="text-align: center">No Material Found</h3>
  <% end %>
</div>

<script>
    function changeStatus(material_id) {
        $.ajax({
            url: 'materials/updateStatus.json',
            dataType: 'json',
            data: {
                id: material_id
            }
        })
    }
    $('#term').autocomplete({
        source: $('#term').data('autocomplete-source')
    });
</script>