config/routes.rb
Rails.application.routes.draw do
    get 'notification/index'
    get 'notification/background_job'
    post 'notification/create'
    root 'statistic#home'
    get 'login', to: 'session#new'
    post 'login', to: 'session#create'
    delete 'logout', to: 'session#destroy'
    resource 'allowances', only: [:show]
    resource 'vouchers', only: [:show, :create]
    resource 'users'
    resource 'dishes'
    resource 'tables'
    resource 'categories'
    resource 'price_change_histories'
    resource 'materials'
    resource 'feed_backs', only: [:show]
    post 'notify_webapp', to: 'pay_pal#notify_webapp'
    get 'refund', to: 'pay_pal#refund'
    get 'rejected_order', to: 'pay_pal#rejected_order'
    get 'send_money', to: 'pay_pal#send_money'
    get 'getEmail', to: 'pay_pal#getEmail'
    get 'balance', to: 'users#user_balance'
    get 'withdraw', to: 'users#with_draw'
    post 'executeSendMoney', to: 'pay_pal#executeSend'
    get 'make_statistic', to: 'statistic#make_statistic'
    get 'setScheduler', to: 'statistic#setScheduler'
    get 'scheduler', to: 'statistic#scheduler'
    get 'home', to: 'statistic#home'
    get 'dashboard', to: 'statistic#index'
    get 'current_order', to: 'statistic#current_order'
    get 'cancel_order', to: 'pay_pal#cancel_order'
    resources :fakes, only: [:index]
    devise_for :users
    require 'sidekiq/web'
    mount Sidekiq::Web => '/side'

    namespace :api do
        scope module: :v1, constraints: ApiConstraint.new(version: :v1) do
            get 'home', to: 'home#index'
            resources :users, only: [:show, :create, :update] do
                collection do
                    get :balance
                    post :add_voucher
                end
            end

            resources :vouchers do
                collection do
                    post :check_balance_code
                end

            end

            resources :feedbacks, only: [:create] do
                
            end
            resources :sessions, only: [:create, :destroy]
            resources :dishes, only: [:index, :show, :update, :destroy] do
                member do
                    get :cutlery
                    get :drinking
                end
                collection do
                    get :by_category
                    get :as_cart
                    get :search_cutlery
                    get :search_drinking
                    get :search_all
                    post :register_reg_token
                    post :disable_dish
                    get :check_dish_available
                    get :dish_suggestion
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :notifications do
                collection do
                    post :register_reg_token
                end
            end

            resources :orders, only: [:create, :index] do
                collection do
                    get :order_history
                    post :dish_done # mon an duoc lam xong
                    post :list_dish_done
                    post :remove_dish # mon an remove khoi menu vi nhet nguyen lieu
                    post :reject_order # order bi reject boi chef
                    get :all_order # get toan bo order
                    post :mark_order_accept
                    post :mark_order_reject
                    get :order_in_time
                    get :is_in_time_order
                    post :fully_refund
                    post :partial_refund
                    get :table_dish
                    post :notify_order_detail_not_available
                    post :mark_order_detail_served
                    post :mark_list_order_detail_served
                    post :create_by_cash
                    post :create_by_voucher
                    post :payed_by_cash
                    post :keep_order_detail
                    post :cash_full_refund
                    post :cash_partial_refund
                end
            end

            resources :materials, only: [:index] do
                collection do
                    post :mark_not_available
                    post :mark_available
                end
            end

        end
    end
end

app/controllers/statistic_controller.rb
class StatisticController < WebApplcationController
  before_action 'authen_user'
  add_breadcrumb "Home", :root_path
  include ConfigBoeHelper

  def current_order
    add_breadcrumb "Current Orders"
    if !params[:term].nil?
      if params[:type] == "table"
        # order_id = OrderDetail.select(:order_id).where('cooking_status = 0 OR  cooking_status = 1').group(:order_id).map(&:order_id)
        # @orders = Order.where(id: order_id).where(table_number: params[:term])
        order_id = Order.where(table_number: params[:term]).map(&:id)
        @order_details = OrderDetail.where(order_id: order_id).where(cooking_status: 0).map {|od| od if od.order.cooking_status == 0}.compact
      else
        @orders = User.find_by(username: params[:term]).orders
        @order_details = OrderDetail.where(order_id: User.find_by(username: params[:term]).orders.map(&:id)).map {|od| od if od.order.cooking_status == 0}.compact
      end
    end
  end

  def home
    if session[:role] == 'admin'
      redirect_to users_path
    end
  end

  def scheduler
    add_breadcrumb "Scheduler"
  end

  def index
    @user = Order.order('sum_total desc').includes(:user).group('users.username').select('users.username').references(:users).sum(:total).first
    @dish = OrderDetail.order('sum_quantity desc').includes(:dish).group('dishes.dish_name').references(:dishes).sum(:quantity).first
    @revenue = Order.sum(:total)
    @visit = Order.count
    add_breadcrumb "Dashboard"
  end

  def setScheduler
    closeTime = params[:closeTime]
    if closeTime != ''
      set_time_close closeTime.split(':')[0], closeTime.split(':')[1]
      render json: {status: 'true'}
    else
      render nothing: true
    end
  end

  def make_statistic
    respond_to do |format|
      format.html {

      }
      format.json {
        type = params[:type]
        duration = params[:duration]
        if type == 'user'
          if duration == 'month'
            render json: Order.order('sum_total desc').includes(:user).group('users.username').select('users.username').references(:users).where('date_part(\'month\', orders.created_at) = date_part(\'month\', current_date)').sum(:total).first(10).to_json
          elsif duration == 'year'
            render json: Order.order('sum_total desc').includes(:user).group('users.username').select('users.username').references(:users).where('date_part(\'year\', orders.created_at) = date_part(\'year\', current_date)').sum(:total).first(10).to_json
          else

          end
        elsif type == 'order'
          if duration == 'month'
            render json: Order.order('sum_total desc').where('date_part(\'month\', orders.created_at) = date_part(\'month\', current_date)').group_by_day_of_week(:created_at, format: "%a").sum(:total).to_json
          elsif duration == 'year'
            render json: Order.order('sum_total desc').where('date_part(\'year\', orders.created_at) = date_part(\'year\', current_date)').group_by_month(:created_at, format: "%b %Y").sum(:total).to_json
          else

          end
        else
          if duration == 'month'
            render json: OrderDetail.order('sum_quantity desc').includes(:dish).group('dishes.dish_name').references(:dishes).where('date_part(\'month\', order_details.created_at) = date_part(\'month\', current_date)').sum(:quantity).first(5).to_json
          elsif duration == 'year'
            render json: OrderDetail.order('sum_quantity desc').includes(:dish).group('dishes.dish_name').references(:dishes).where('date_part(\'year\', order_details.created_at) = date_part(\'year\', current_date)').sum(:quantity).first(5).to_json
          else

          end
        end
      }
    end
  end
end

app/views/statistic/current_order.html.erb
<style>
  label {
    font-weight: bold;
  }
</style>
<div id="unclose_modal" class="modal">
  <div class="modal-content" style="text-align: center;">
    <h5>Please Wait...</h5>
    <div class="preloader-wrapper big active">
      <div class="spinner-layer spinner-blue-only">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div>
        <div class="gap-patch">
          <div class="circle"></div>
        </div>
        <div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
  <div class="col s6 right">
    <div class="input-field" style="margin-top: 0">
      <%= form_tag(current_order_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], style: 'width: 60%;', placeholder: 'Search', data: {autocomplete_source: Dish.order(:dish_name).map(&:dish_name)} %>
          <div class="col s3">
            <select name="type" onchange="onSelectType()" id="type">
              <% if params[:type] == "dish" %>
                  <option value="dish" selected>Username</option>
              <% else %>
                  <option value="dish">Username</option>
              <% end %>
              <% if params[:type] == "table" %>
                  <option value="table" selected>Table</option>
              <% else %>
                  <option value="table">Table</option>
              <% end %>
            </select>
          </div>
          <button type="submit" class="btn-floating waves-effect waves-light">
            <i class="material-icons">search</i>
          </button>
      <% end %>
    </div>
  </div>
</div>
<div style="padding: 0% 5%">
  <% if (!@orders.nil? && @orders.size > 0) || (!@order_details.nil? && @order_details.size > 0) %>
      <div class="card">
        <div class="card-content">
          <span class="card-title">Current Order</span>
          <% if params[:type] == "table" %>
              <table id="table" class="bordered striped">
                <thead>
                <th style="text-align: center;">User</th>
                <th style="text-align: center;">Dish</th>
                <th style="text-align: center;">Quantity</th>
                <th></th>
                </thead>
                <tbody id="tbody">
                <% @order_details.each do |order_detail| %>
                    <tr>
                      <td style="text-align: center"><%= order_detail.order.user.username %></td>
                      <td style="text-align: center"><%= order_detail.dish.dish_name %></td>
                      <td style="text-align: center"><%= order_detail.quantity_not_serve %></td>
                      <td style="text-align: center">
                        <a href="cancel_order?order_detail_id=<%= order_detail.id %>&term=<%= params[:term] %>&type=<%= params[:type] %>" onclick="$('#unclose_modal').modal('open');">
                          <input type="button" value="cancel" class="btn red">
                        </a>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% elsif params[:type] == "dish" %>
              <table id="table" class="bordered striped">
                <thead>
                <th style="text-align: center; width: 15%">Table Number</th>
                <th style="text-align: center;">Dish</th>
                <th style="text-align: center;">Quantity</th>
                <th></th>
                </thead>
                <tbody id="tbody">
                <% @order_details.each do |order_detail| %>
                    <tr>
                      <td style="text-align: center"><%= order_detail.order.table_number %></td>
                      <td style="text-align: center"><%= order_detail.dish.dish_name %></td>
                      <td style="text-align: center"><%= order_detail.quantity_not_serve %></td>
                      <td style="text-align: center">
                        <a href="cancel_order?order_detail_id=<%= order_detail.id %>&term=<%= params[:term] %>&type=<%= params[:type] %>" onclick="$('#unclose_modal').modal('open');">
                          <input type="button" value="cancel" class="btn red">
                        </a>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% end %>
        </div>
      </div>
  <% elsif !params[:term].nil? %>
      <h5 id="available" style="text-align: center;">Not Available</h5>
  <% end %>
</div>
<script>
    $('#term').autocomplete({
        source: $('#term').data('autocomplete-source')
    });

    function onSelectType() {
        var selected = $('#type').find(":selected").text();
        if (selected == "Dish") {
            $('#term').autocomplete({
                source: $('#term').data('autocomplete-source')
            });
        } else {
            console.log("destroy");
            $('#term').autocomplete({disabled: true});
        }
    }
</script>

app/views/statistic/home.html.erb
<div class="left" style="margin-left: 1%; font-size: 18px">
  <%= render_breadcrumbs :separator => ' > ' %>
</div>

app/views/statistic/index.html.erb
<div class="row" style="margin-top: 0;">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="row">
  <div class="col s4">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text center-align">
        <span class="card-title">TOP USER</span>
        <% if !@user.nil? %>
            <p><%= @user[0] %></p>
            <p>Total: <%= @user[1] %>VND</p>
        <% else %>
            <p>N/A</p>
            <p>Total: N/A</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col s4">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text center-align">
        <span class="card-title">TOP DISH</span>
        <% if !@dish.nil? %>
            <p><%= @dish[0] %></p>
            <p>Total quantity: <%= @dish[1] %></p>
        <% else %>
            <p>N/A</p>
            <p>Total quantity: N/A</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col s4">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text center-align">
        <span class="card-title">Revenue</span>
        <% if !@visit.nil? %>
            <p>Total order: <%= @visit %></p>
        <% else %>
            <p>Total order: N/A</p>
        <% end %>
        <% if !@revenue.nil? %>
            <p>Total income: <%= @revenue %></p>
        <% else %>
            <p>Total income: N/A</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% @date = Date.today %>
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title grey-text text-darken-4">Revenue
            <span class="switch right" onchange="make_statistic('order', 'revenue_duration', 'revenue_chart')">
              <label>
                Month <%= @date.strftime("%B") %>
                <input type="checkbox" id="revenue_duration">
                <span class="lever"></span>
                Year <%= @date.year %>
              </label>
            </span>
        </span>
        <div id="data" class="row">
          <%= line_chart Order.where('date_part(\'month\', orders.created_at) = date_part(\'month\', current_date)').group_by_day_of_week(:created_at, format: "%a").sum(:total), id: 'revenue_chart' %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s7">
    <div class="card">
      <div class="card-content">
        <span class="card-title grey-text text-darken-4">Top 10 Diner
            <span class="switch right" onchange="make_statistic('user', 'user_duration', 'user_chart')">
              <label>
                Month <%= @date.strftime("%B") %>
                <input type="checkbox" id="user_duration">
                <span class="lever"></span>
                Year <%= @date.year %>
              </label>
            </span>
        </span>
        <div id="data" class="row">
          <%= bar_chart Order.order('sum_total desc').includes(:user).group('users.username').select('users.username').references(:users).where('date_part(\'month\', orders.created_at) = date_part(\'month\', current_date)').sum(:total).first(10), id: 'user_chart' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col s5">
    <div class="card">
      <div class="card-content">
        <span class="card-title grey-text text-darken-4">Top 5 Dish
            <span class="switch right" onchange="make_statistic('dish', 'dish_duration', 'dish_chart')">
              <label>
                Month <%= @date.strftime("%B") %>
                <input type="checkbox" id="dish_duration">
                <span class="lever"></span>
                Year <%= @date.year %>
              </label>
            </span>
        </span>
        <div id="data" class="row">
          <%= pie_chart OrderDetail.includes(:dish).group('dishes.dish_name').references(:dishes).where('date_part(\'month\', order_details.created_at) = date_part(\'month\', current_date)').sum(:quantity).first(5), id: 'dish_chart' %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    function make_statistic(type, duration_name, chart_name) {
        if ($('#' + duration_name).is(':checked')) {
            duration = 'year';
        } else {
            duration = 'month';
        }
        $.ajax({
            url: '/make_statistic.json',
            dataType: 'json',
            data: {
                type: type,
                duration: duration
            },
            success: function (data) {
                var chart = Chartkick.charts[chart_name];
                chart.updateData(data);
            }
        })
    }

</script>

app/views/statistic/scheduler.html.erb
<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.9&appId=146799929207310";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script>
    // This is called with the results from from FB.getLoginStatus().
    function statusChangeCallback(response) {
        console.log('statusChangeCallback');
        console.log(response);
        // The response object is returned with a status field that lets the
        // app know the current login status of the person.
        // Full docs on the response object can be found in the documentation
        // for FB.getLoginStatus().
        if (response.status === 'connected') {
            // Logged into your app and Facebook.
            testAPI();
        } else {
            // The person is not logged into your app or we are unable to tell.
            document.getElementById('status').innerHTML = 'Please log ' +
                'into this app.';
        }
    }

    // This function is called when someone finishes with the Login
    // Button.  See the onlogin handler attached to it in the sample
    // code below.
    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            statusChangeCallback(response);
        });
    }

    window.fbAsyncInit = function () {
        FB.init({
            appId: '{your-app-id}',
            cookie: true,  // enable cookies to allow the server to access
                           // the session
            xfbml: true,  // parse social plugins on this page
            version: 'v2.8' // use graph api version 2.8
        });

        // Now that we've initialized the JavaScript SDK, we call
        // FB.getLoginStatus().  This function gets the state of the
        // person visiting this page and can return one of three states to
        // the callback you provide.  They can be:
        //
        // 1. Logged into your app ('connected')
        // 2. Logged into Facebook, but not your app ('not_authorized')
        // 3. Not logged into Facebook and can't tell if they are logged into
        //    your app or not.
        //
        // These three cases are handled in the callback function.

        FB.getLoginStatus(function (response) {
            statusChangeCallback(response);
        });

    };

    // Load the SDK asynchronously
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.
    function testAPI() {
        console.log('Welcome!  Fetching your information.... ');
        FB.api('/me', function (response) {
            console.log('Successful login for: ' + response.name);
            document.getElementById('status').innerHTML =
                'Thanks for logging in, ' + response.name + '!';
        });
    }
</script>
<style>
  label {
    font-weight: bold;
  }
</style>
<div class="row">
  <div class="left" style="margin-left: 1%; font-size: 18px;">
    <%= render_breadcrumbs :separator => ' > ' %>
  </div>
</div>
<div class="container">
  <div class="card">
    <div class="card-content">
      <span class="card-title">Restaurant Schedule</span>
      <div class="row">
        <div class="input-field col s6">
          <b>Close Time *</b><input type="time" id="close_time" placeholder="Close Time" required="required">
        </div>
      </div>
    </div>
    <div class="card-action">
      <button class="btn" onclick="setTimeScheduler()">Set</button>
      <!--<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>-->
    </div>
  </div>
</div>
<script>
    function setTimeScheduler() {
        var closeTime = $('#close_time').val();
        if (closeTime == '') {
            alert('Please Insert Time');
        }
        $.ajax({
            url: 'setScheduler',
            dataType: 'json',
            data: {
                closeTime: closeTime
            },
            success: function (data) {
                if (data.status) {
                    alert('Set Scheduler Successfully')
                }
            }
        })
    }
</script>